import type { Notice } from '@/types/notice';

export const NOTICE_MOCK_DATA: Notice[] = [
    {
        id: 1,
        title: '신규 상품 출시 안내',
        content: '새로운 프리미엄 라인의 상품들이 출시되었습니다. 특별 할인 혜택과 함께 만나보세요.',
        writer: 'admin',
        createAt: '2024-12-15',
    },
    {
        id: 2,
        title: '배송 지연 안내',
        content: '연말 물량 증가로 인해 일부 지역의 배송이 1-2일 지연될 수 있습니다. 양해 부탁드립니다.',
        writer: 'admin',
        createAt: '2024-12-10',
    },
    {
        id: 3,
        title: '고객센터 운영시간 변경 안내',
        content: '12월 25일부터 고객센터 운영시간이 평일 09:00~17:00로 변경됩니다.',
        writer: 'manager',
        createAt: '2024-12-08',
    },
    {
        id: 4,
        title: '회원 등급 혜택 개편 안내',
        content: '더 나은 혜택 제공을 위해 회원 등급 시스템이 개편됩니다. 기존 회원님들의 등급은 유지됩니다.',
        writer: 'admin',
        createAt: '2024-12-05',
    },
    {
        id: 5,
        title: '겨울 시즌 특가 세일 시작',
        content: '겨울 상품 최대 50% 할인! 12월 31일까지 진행되니 놓치지 마세요.',
        writer: 'admin',
        createAt: '2024-12-01',
    },
    {
        id: 6,
        title: '개인정보 처리방침 변경 안내',
        content: '개인정보 보호법 개정에 따라 개인정보 처리방침이 일부 변경되었습니다.',
        writer: 'admin',
        createAt: '2024-11-28',
    },
    {
        id: 7,
        title: '시스템 점검 안내',
        content: '11월 30일 새벽 02:00~06:00 시스템 점검으로 인해 서비스 이용이 제한됩니다.',
        writer: 'manager',
        createAt: '2024-11-25',
    },
    {
        id: 8,
        title: '신규 결제 수단 추가',
        content: '카카오페이, 네이버페이 결제 서비스가 추가되었습니다. 더 편리하게 이용하세요.',
        writer: 'admin',
        createAt: '2024-11-20',
    },
    {
        id: 9,
        title: '블랙프라이데이 특별 이벤트',
        content: '11월 29일 하루 한정! 전 상품 추가 20% 할인 쿠폰을 지급해드립니다.',
        writer: 'admin',
        createAt: '2024-11-18',
    },
    {
        id: 10,
        title: '반품/교환 정책 개선 안내',
        content: '고객 만족도 향상을 위해 반품/교환 기간이 7일에서 14일로 연장됩니다.',
        writer: 'admin',
        createAt: '2024-11-15',
    },
    {
        id: 11,
        title: '모바일 앱 업데이트 안내',
        content: '더 빠르고 안정적인 서비스를 위해 모바일 앱이 업데이트되었습니다.',
        writer: 'developer',
        createAt: '2024-11-12',
    },
    {
        id: 12,
        title: '리뷰 작성 이벤트 당첨자 발표',
        content: '10월 리뷰 작성 이벤트 당첨자를 발표합니다. 당첨자분들께는 개별 연락드리겠습니다.',
        writer: 'admin',
        createAt: '2024-11-08',
    },
    {
        id: 13,
        title: '추석 연휴 배송 및 고객센터 운영 안내',
        content: '추석 연휴 기간 동안의 배송 일정과 고객센터 운영시간을 안내드립니다.',
        writer: 'admin',
        createAt: '2024-09-10',
    },
    {
        id: 14,
        title: '여름 신상품 론칭 기념 이벤트',
        content: '시원한 여름을 위한 신상품 출시! 론칭 기념 특가로 만나보세요.',
        writer: 'admin',
        createAt: '2024-06-15',
    },
    {
        id: 15,
        title: '회원가입 축하 쿠폰 정책 변경',
        content: '신규 회원가입 시 지급되는 쿠폰 혜택이 개선되었습니다.',
        writer: 'admin',
        createAt: '2024-05-20',
    },
    {
        id: 16,
        title: '어린이날 특별 할인 이벤트',
        content: '5월 5일 어린이날을 맞아 키즈 상품 특별 할인 이벤트를 진행합니다.',
        writer: 'admin',
        createAt: '2024-05-01',
    },
    {
        id: 17,
        title: '봄맞이 대청소 이벤트',
        content: '집안 정리에 필요한 모든 용품을 한 번에! 봄맞이 특가 이벤트입니다.',
        writer: 'admin',
        createAt: '2024-03-15',
    },
    {
        id: 18,
        title: '신규 브랜드 입점 안내',
        content: '고객님들이 사랑하는 인기 브랜드들이 새롭게 입점했습니다.',
        writer: 'admin',
        createAt: '2024-02-28',
    },
    {
        id: 19,
        title: '설날 연휴 서비스 운영 안내',
        content: '설날 연휴 기간 동안의 주문, 배송, 고객센터 운영 일정을 안내드립니다.',
        writer: 'admin',
        createAt: '2024-02-05',
    },
    {
        id: 20,
        title: '2024년 새해 인사 및 이벤트',
        content: '새해 복 많이 받으세요! 2024년을 맞아 특별한 신년 이벤트를 준비했습니다.',
        writer: 'admin',
        createAt: '2024-01-01',
    },
];
