import type { ProductItemProps } from '@/types/product';

export const PRODUCT_MOCK_DATA: ProductItemProps[] = [
    {
        id: 1,
        name: '레고트 누프레임 커플잔 2P',
        discountRate: 20,
        price: 32000,
        originalPrice: 40000,
        starRating: 4.5,
        reviewCount: 120,
        thumbnailUrl: '/images/product-1.jpg',
        badges: ['Best'],
    },
    {
        id: 2,
        name: '모던 스톤웨어 접시 세트',
        discountRate: 15,
        price: 25500,
        originalPrice: 30000,
        starRating: 4.3,
        reviewCount: 85,
        thumbnailUrl: '/images/product-2.jpg',
        badges: ['New'],
    },
    {
        id: 3,
        name: '에코 우드 컵 4P 세트',
        discountRate: 10,
        price: 18000,
        originalPrice: 20000,
        starRating: 4.8,
        reviewCount: 200,
        thumbnailUrl: '/images/product-3.jpg',
    },
    {
        id: 4,
        name: '클래식 도자기 찻잔 세트',
        discountRate: 25,
        price: 15000,
        originalPrice: 20000,
        starRating: 4.2,
        reviewCount: 60,
        thumbnailUrl: '/images/product-4.jpg',
        badges: ['Best', 'New'],
    },
    {
        id: 5,
        name: '프리미엄 코르크 컵받침 세트',
        discountRate: 30,
        price: 14000,
        originalPrice: 20000,
        starRating: 4.7,
        reviewCount: 150,
        thumbnailUrl: '/images/product-1.jpg',
        badges: ['Best'],
    },
    {
        id: 6,
        name: '럭셔리 실버 커틀러리 세트',
        discountRate: 18,
        price: 65600,
        originalPrice: 80000,
        starRating: 4.9,
        reviewCount: 95,
        thumbnailUrl: '/images/product-2.jpg',
        badges: ['Premium'],
    },
    {
        id: 7,
        name: '대나무 브레드보드 라지',
        discountRate: 12,
        price: 22000,
        originalPrice: 25000,
        starRating: 4.4,
        reviewCount: 180,
        thumbnailUrl: '/images/product-3.jpg',
        badges: ['Eco'],
    },
    {
        id: 8,
        name: '핸드메이드 세라믹 볼 세트',
        discountRate: 22,
        price: 31200,
        originalPrice: 40000,
        starRating: 4.6,
        reviewCount: 110,
        thumbnailUrl: '/images/product-4.jpg',
        badges: ['Handmade'],
    },
    {
        id: 9,
        name: '미니멀 글라스 텀블러 6P',
        discountRate: 8,
        price: 27600,
        originalPrice: 30000,
        starRating: 4.1,
        reviewCount: 75,
        thumbnailUrl: '/images/product-1.jpg',
        badges: ['New'],
    },
    {
        id: 10,
        name: '빈티지 주철 팬 세트',
        discountRate: 35,
        price: 78000,
        originalPrice: 120000,
        starRating: 4.8,
        reviewCount: 230,
        thumbnailUrl: '/images/product-2.jpg',
        badges: ['Best', 'Sale'],
    },
    {
        id: 11,
        name: '천연 라탄 플레이트 매트',
        discountRate: 5,
        price: 19000,
        originalPrice: 20000,
        starRating: 4.0,
        reviewCount: 45,
        thumbnailUrl: '/images/product-3.jpg',
        badges: ['Natural'],
    },
    {
        id: 12,
        name: '모던 마블 치즈보드 세트',
        discountRate: 28,
        price: 36000,
        originalPrice: 50000,
        starRating: 4.7,
        reviewCount: 135,
        thumbnailUrl: '/images/product-4.jpg',
        badges: ['Premium', 'Best'],
    },
    {
        id: 13,
        name: '실리콘 와인 디캔터',
        discountRate: 15,
        price: 42500,
        originalPrice: 50000,
        starRating: 4.3,
        reviewCount: 88,
        thumbnailUrl: '/images/product-1.jpg',
        badges: ['Innovation'],
    },
    {
        id: 14,
        name: '스테인리스 믹싱볼 3종',
        discountRate: 20,
        price: 24000,
        originalPrice: 30000,
        starRating: 4.5,
        reviewCount: 165,
        thumbnailUrl: '/images/product-2.jpg',
        badges: ['Professional'],
    },
    {
        id: 15,
        name: '오가닉 코튼 테이블러너',
        discountRate: 12,
        price: 17600,
        originalPrice: 20000,
        starRating: 4.2,
        reviewCount: 92,
        thumbnailUrl: '/images/product-3.jpg',
        badges: ['Organic', 'Eco'],
    },
    {
        id: 16,
        name: '핸드크래프트 유리 화병 세트',
        discountRate: 40,
        price: 48000,
        originalPrice: 80000,
        starRating: 4.9,
        reviewCount: 210,
        thumbnailUrl: '/images/product-4.jpg',
        badges: ['Handcraft', 'Best', 'Sale'],
    },
];
