import type { Review } from '@/types/review';

export const REVIEW_MOCK_DATA: Review[] = [
    {
        isBest: true,
        productId: 1,
        productName: '레고트 누프레임 커플잔 2P',
        productOption: '레드',
        productImage: '/images/product-1.jpg',
        rating: 5,
        contents: '정말 예쁜 커플잔이에요! 레고트 디자인이 너무 마음에 들어요.',
        writer: 'test_user',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-10-01',
    },
    {
        isBest: false,
        productId: 3,
        productName: '에코 우드 컵 4P 세트',
        productOption: '내추럴',
        productImage: '/images/product-3.jpg',
        rating: 5,
        contents: '친환경적이고 디자인도 너무 예뻐요. 손에 잡히는 느낌도 좋고 추천합니다!',
        writer: 'eco_lover',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-11-15',
    },
    {
        isBest: true,
        productId: 10,
        productName: '빈티지 주철 팬 세트',
        productOption: '블랙',
        productImage: '/images/product-2.jpg',
        rating: 5,
        contents: '요리하기 정말 좋아요. 열전도가 우수하고 무게감도 적당해서 만족합니다.',
        writer: 'cooking_master',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-12-03',
    },
    {
        isBest: false,
        productId: 7,
        productName: '대나무 브레드보드 라지',
        productOption: '라지',
        productImage: '/images/product-4.jpg',
        rating: 4,
        contents: '크기가 딱 좋고 대나무 소재라 위생적이에요. 빵 자르기 편해요.',
        writer: 'bread_lover',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-11-28',
    },
    {
        isBest: false,
        productId: 2,
        productName: '모던 스톤웨어 접시 세트',
        productOption: '그레이',
        productImage: '/images/product-1.jpg',
        rating: 4,
        contents: '디자인은 예쁜데 생각보다 무거워요. 그래도 고급스러운 느낌이 좋습니다.',
        writer: 'modern_style',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-12-10',
    },
    {
        isBest: true,
        productId: 16,
        productName: '핸드크래프트 유리 화병 세트',
        productOption: '클리어',
        productImage: '/images/product-5.jpg',
        rating: 5,
        contents: '수공예품이라 그런지 정말 특별해요. 인테리어 소품으로 완벽합니다!',
        writer: 'interior_fan',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-12-15',
    },
    {
        isBest: false,
        productId: 5,
        productName: '프리미엄 코르크 컵받침 세트',
        productOption: '내추럴',
        productImage: '/images/product-3.jpg',
        rating: 4,
        contents: '코르크 소재가 물을 잘 흡수해서 실용적이에요. 디자인도 심플하고 좋아요.',
        writer: 'practical_user',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2023-12-20',
    },
    {
        isBest: false,
        productId: 12,
        productName: '모던 마블 치즈보드 세트',
        productOption: '화이트',
        productImage: '/images/product-2.jpg',
        rating: 5,
        contents: '마블 무늬가 정말 고급스러워요. 치즈 파티할 때 분위기가 확실히 다르네요.',
        writer: 'party_host',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-01-05',
    },
    {
        isBest: true,
        productId: 4,
        productName: '클래식 도자기 찻잔 세트',
        productOption: '화이트',
        productImage: '/images/product-4.jpg',
        rating: 5,
        contents: '클래식한 디자인이 마음에 들어요. 차 마실 때 우아한 기분이 듭니다.',
        writer: 'tea_time',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-01-12',
    },
    {
        isBest: false,
        productId: 14,
        productName: '스테인리스 믹싱볼 3종',
        productOption: '실버',
        productImage: '/images/product-1.jpg',
        rating: 3,
        contents: '실용적이긴 한데 디자인이 좀 심심해요. 기능적으로는 만족합니다.',
        writer: 'kitchen_helper',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-01-18',
    },
    {
        isBest: false,
        productId: 8,
        productName: '핸드메이드 세라믹 볼 세트',
        productOption: '베이지',
        productImage: '/images/product-5.jpg',
        rating: 5,
        contents: '핸드메이드라서 하나하나 다 특별해요. 질감도 좋고 색상도 예뻐요.',
        writer: 'handmade_lover',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-01-25',
    },
    {
        isBest: true,
        productId: 6,
        productName: '럭셔리 실버 커틀러리 세트',
        productOption: '실버',
        productImage: '/images/product-3.jpg',
        rating: 5,
        contents: '정말 고급스러워요! 손님 초대할 때 쓰면 분위기가 확실히 달라집니다.',
        writer: 'luxury_life',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-02-01',
    },
    {
        isBest: false,
        productId: 11,
        productName: '천연 라탄 플레이트 매트',
        productOption: '내추럴',
        productImage: '/images/product-2.jpg',
        rating: 4,
        contents: '천연 소재라 좋은데 관리가 좀 까다로워요. 디자인은 예뻐요.',
        writer: 'natural_style',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-02-08',
    },
    {
        isBest: false,
        productId: 9,
        productName: '미니멀 글라스 텀블러 6P',
        productOption: '클리어',
        productImage: '/images/product-4.jpg',
        rating: 4,
        contents: '심플하고 깔끔해서 어떤 음료를 마셔도 잘 어울려요. 6개 세트라 좋아요.',
        writer: 'minimal_fan',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-02-14',
    },
    {
        isBest: true,
        productId: 13,
        productName: '실리콘 와인 디캔터',
        productOption: '클리어',
        productImage: '/images/product-1.jpg',
        rating: 5,
        contents: '와인 맛이 확실히 달라져요. 실리콘 소재라 안전하고 세척도 편해요.',
        writer: 'wine_lover',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-02-20',
    },
    {
        isBest: false,
        productId: 15,
        productName: '오가닉 코튼 테이블러너',
        productOption: '아이보리',
        productImage: '/images/product-5.jpg',
        rating: 3,
        contents: '오가닉 소재는 좋은데 생각보다 얇아서 아쉬워요. 색상은 예뻐요.',
        writer: 'organic_user',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-02-25',
    },
    {
        isBest: false,
        productId: 1,
        productName: '레고트 누프레임 커플잔 2P',
        productOption: '블루',
        productImage: '/images/product-3.jpg',
        rating: 4,
        contents: '커플잔으로 딱이에요. 색상도 예쁘고 크기도 적당해서 만족합니다.',
        writer: 'couple_gift',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-03-05',
    },
    {
        isBest: true,
        productId: 10,
        productName: '빈티지 주철 팬 세트',
        productOption: '브라운',
        productImage: '/images/product-2.jpg',
        rating: 5,
        contents: '정말 최고예요! 스테이크 구울 때 완벽한 마이야르 반응이 일어나요.',
        writer: 'steak_master',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-03-12',
    },
    {
        isBest: false,
        productId: 3,
        productName: '에코 우드 컵 4P 세트',
        productOption: '다크우드',
        productImage: '/images/product-4.jpg',
        rating: 3,
        contents: '친환경 소재는 좋은데 나무 냄새가 조금 나요. 시간이 지나면 괜찮을 것 같아요.',
        writer: 'eco_conscious',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-03-18',
    },
    {
        isBest: false,
        productId: 7,
        productName: '대나무 브레드보드 라지',
        productOption: '라지',
        productImage: '/images/product-1.jpg',
        rating: 5,
        contents: '크기가 넉넉해서 빵뿐만 아니라 야채 써는 용도로도 사용해요. 추천!',
        writer: 'kitchen_pro',
        reviewImage: '/images/review-image.jpg',
        createdAt: '2024-03-25',
    },
];
